console.log(false == "" ) 
console.log(false == [])  
console.log(false == {})  
console.log("" == 0)      
console.log("" == [])    
console.log("" == {})    
console.log(0 == [])     
console.log(0 == {})      
console.log(0 == null)    